/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScLabelRecord extends org.jooq.impl.UpdatableRecordImpl<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScLabelRecord> implements org.jooq.Record2<java.math.BigInteger, java.lang.String> {

	private static final long serialVersionUID = 1129268949;

	/**
	 * Setter for <code>AE2.SC_LABEL.ID</code>. 
	 */
	public void setId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>AE2.SC_LABEL.ID</code>. 
	 */
	public java.math.BigInteger getId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>AE2.SC_LABEL.NAME</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>AE2.SC_LABEL.NAME</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.math.BigInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.math.BigInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ScLabelRecord
	 */
	public ScLabelRecord() {
		super(uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL);
	}
}
