/*
 * This file is generated by jOOQ.
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataFilesRecord extends UpdatableRecordImpl<DataFilesRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ae_autosubs.data_files.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ae_autosubs.data_files.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ae_autosubs.data_files.experiment_id</code>.
     */
    public void setExperimentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ae_autosubs.data_files.experiment_id</code>.
     */
    public Integer getExperimentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ae_autosubs.data_files.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ae_autosubs.data_files.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ae_autosubs.data_files.is_unpacked</code>.
     */
    public void setIsUnpacked(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ae_autosubs.data_files.is_unpacked</code>.
     */
    public Integer getIsUnpacked() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ae_autosubs.data_files.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ae_autosubs.data_files.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DataFiles.DATA_FILES.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DataFiles.DATA_FILES.EXPERIMENT_ID;
    }

    @Override
    public Field<String> field3() {
        return DataFiles.DATA_FILES.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return DataFiles.DATA_FILES.IS_UNPACKED;
    }

    @Override
    public Field<Integer> field5() {
        return DataFiles.DATA_FILES.IS_DELETED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getExperimentId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getIsUnpacked();
    }

    @Override
    public Integer component5() {
        return getIsDeleted();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getExperimentId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getIsUnpacked();
    }

    @Override
    public Integer value5() {
        return getIsDeleted();
    }

    @Override
    public DataFilesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DataFilesRecord value2(Integer value) {
        setExperimentId(value);
        return this;
    }

    @Override
    public DataFilesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public DataFilesRecord value4(Integer value) {
        setIsUnpacked(value);
        return this;
    }

    @Override
    public DataFilesRecord value5(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public DataFilesRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataFilesRecord
     */
    public DataFilesRecord() {
        super(DataFiles.DATA_FILES);
    }

    /**
     * Create a detached, initialised DataFilesRecord
     */
    public DataFilesRecord(Integer id, Integer experimentId, String name, Integer isUnpacked, Integer isDeleted) {
        super(DataFiles.DATA_FILES);

        setId(id);
        setExperimentId(experimentId);
        setName(name);
        setIsUnpacked(isUnpacked);
        setIsDeleted(isDeleted);
    }
}
