/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentsRecord extends org.jooq.impl.UpdatableRecordImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.ExperimentsRecord> {

	private static final long serialVersionUID = 1597946984;

	/**
	 * Setter for <code>ae_autosubs.experiments.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.accession</code>. 
	 */
	public void setAccession(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.accession</code>. 
	 */
	public java.lang.String getAccession() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.user_id</code>. 
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.user_id</code>. 
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.checker_score</code>. 
	 */
	public void setCheckerScore(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.checker_score</code>. 
	 */
	public java.lang.Integer getCheckerScore() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.software</code>. 
	 */
	public void setSoftware(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.software</code>. 
	 */
	public java.lang.String getSoftware() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.status</code>. 
	 */
	public void setStatus(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.status</code>. 
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.data_warehouse_ready</code>. 
	 */
	public void setDataWarehouseReady(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.data_warehouse_ready</code>. 
	 */
	public java.lang.Integer getDataWarehouseReady() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.date_last_edited</code>. 
	 */
	public void setDateLastEdited(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.date_last_edited</code>. 
	 */
	public java.sql.Timestamp getDateLastEdited() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.date_submitted</code>. 
	 */
	public void setDateSubmitted(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.date_submitted</code>. 
	 */
	public java.sql.Timestamp getDateSubmitted() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.date_last_processed</code>. 
	 */
	public void setDateLastProcessed(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.date_last_processed</code>. 
	 */
	public java.sql.Timestamp getDateLastProcessed() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.in_curation</code>. 
	 */
	public void setInCuration(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.in_curation</code>. 
	 */
	public java.lang.Integer getInCuration() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.curator</code>. 
	 */
	public void setCurator(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.curator</code>. 
	 */
	public java.lang.String getCurator() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.comment</code>. 
	 */
	public void setComment(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.comment</code>. 
	 */
	public java.lang.String getComment() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.experiment_type</code>. 
	 */
	public void setExperimentType(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.experiment_type</code>. 
	 */
	public java.lang.String getExperimentType() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.miamexpress_login</code>. 
	 */
	public void setMiamexpressLogin(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.miamexpress_login</code>. 
	 */
	public java.lang.String getMiamexpressLogin() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.miamexpress_subid</code>. 
	 */
	public void setMiamexpressSubid(java.lang.Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.miamexpress_subid</code>. 
	 */
	public java.lang.Integer getMiamexpressSubid() {
		return (java.lang.Integer) getValue(16);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.is_affymetrix</code>. 
	 */
	public void setIsAffymetrix(java.lang.Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.is_affymetrix</code>. 
	 */
	public java.lang.Integer getIsAffymetrix() {
		return (java.lang.Integer) getValue(17);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.is_uhts</code>. 
	 */
	public void setIsUhts(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.is_uhts</code>. 
	 */
	public java.lang.Integer getIsUhts() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.use_native_datafiles</code>. 
	 */
	public void setUseNativeDatafiles(java.lang.Integer value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.use_native_datafiles</code>. 
	 */
	public java.lang.Integer getUseNativeDatafiles() {
		return (java.lang.Integer) getValue(19);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.is_mx_batchloader</code>. 
	 */
	public void setIsMxBatchloader(java.lang.Integer value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.is_mx_batchloader</code>. 
	 */
	public java.lang.Integer getIsMxBatchloader() {
		return (java.lang.Integer) getValue(20);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.is_deleted</code>. 
	 */
	public void setIsDeleted(java.lang.Integer value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.is_deleted</code>. 
	 */
	public java.lang.Integer getIsDeleted() {
		return (java.lang.Integer) getValue(21);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.miame_score</code>. 
	 */
	public void setMiameScore(java.lang.Integer value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.miame_score</code>. 
	 */
	public java.lang.Integer getMiameScore() {
		return (java.lang.Integer) getValue(22);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.in_data_warehouse</code>. 
	 */
	public void setInDataWarehouse(java.lang.Integer value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.in_data_warehouse</code>. 
	 */
	public java.lang.Integer getInDataWarehouse() {
		return (java.lang.Integer) getValue(23);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.num_submissions</code>. 
	 */
	public void setNumSubmissions(java.lang.Integer value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.num_submissions</code>. 
	 */
	public java.lang.Integer getNumSubmissions() {
		return (java.lang.Integer) getValue(24);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.submitter_description</code>. 
	 */
	public void setSubmitterDescription(java.lang.String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.submitter_description</code>. 
	 */
	public java.lang.String getSubmitterDescription() {
		return (java.lang.String) getValue(25);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.curated_name</code>. 
	 */
	public void setCuratedName(java.lang.String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.curated_name</code>. 
	 */
	public java.lang.String getCuratedName() {
		return (java.lang.String) getValue(26);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.num_samples</code>. 
	 */
	public void setNumSamples(java.lang.Integer value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.num_samples</code>. 
	 */
	public java.lang.Integer getNumSamples() {
		return (java.lang.Integer) getValue(27);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.num_hybridizations</code>. 
	 */
	public void setNumHybridizations(java.lang.Integer value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.num_hybridizations</code>. 
	 */
	public java.lang.Integer getNumHybridizations() {
		return (java.lang.Integer) getValue(28);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.has_raw_data</code>. 
	 */
	public void setHasRawData(java.lang.Integer value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.has_raw_data</code>. 
	 */
	public java.lang.Integer getHasRawData() {
		return (java.lang.Integer) getValue(29);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.has_processed_data</code>. 
	 */
	public void setHasProcessedData(java.lang.Integer value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.has_processed_data</code>. 
	 */
	public java.lang.Integer getHasProcessedData() {
		return (java.lang.Integer) getValue(30);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.has_gds</code>. 
	 */
	public void setHasGds(java.lang.Byte value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.has_gds</code>. 
	 */
	public java.lang.Byte getHasGds() {
		return (java.lang.Byte) getValue(31);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.release_date</code>. 
	 */
	public void setReleaseDate(java.sql.Timestamp value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.release_date</code>. 
	 */
	public java.sql.Timestamp getReleaseDate() {
		return (java.sql.Timestamp) getValue(32);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.is_released</code>. 
	 */
	public void setIsReleased(java.lang.Integer value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.is_released</code>. 
	 */
	public java.lang.Integer getIsReleased() {
		return (java.lang.Integer) getValue(33);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.ae_miame_score</code>. 
	 */
	public void setAeMiameScore(java.lang.Integer value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.ae_miame_score</code>. 
	 */
	public java.lang.Integer getAeMiameScore() {
		return (java.lang.Integer) getValue(34);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.migration_status</code>. 
	 */
	public void setMigrationStatus(java.lang.String value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.migration_status</code>. 
	 */
	public java.lang.String getMigrationStatus() {
		return (java.lang.String) getValue(35);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.migration_comment</code>. 
	 */
	public void setMigrationComment(java.lang.String value) {
		setValue(36, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.migration_comment</code>. 
	 */
	public java.lang.String getMigrationComment() {
		return (java.lang.String) getValue(36);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.migration_source</code>. 
	 */
	public void setMigrationSource(java.lang.String value) {
		setValue(37, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.migration_source</code>. 
	 */
	public java.lang.String getMigrationSource() {
		return (java.lang.String) getValue(37);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.file_to_load</code>. 
	 */
	public void setFileToLoad(java.lang.String value) {
		setValue(38, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.file_to_load</code>. 
	 */
	public java.lang.String getFileToLoad() {
		return (java.lang.String) getValue(38);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.atlas_fail_score</code>. 
	 */
	public void setAtlasFailScore(java.lang.String value) {
		setValue(39, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.atlas_fail_score</code>. 
	 */
	public java.lang.String getAtlasFailScore() {
		return (java.lang.String) getValue(39);
	}

	/**
	 * Setter for <code>ae_autosubs.experiments.annotare_submission_id</code>. 
	 */
	public void setAnnotareSubmissionId(java.lang.Integer value) {
		setValue(40, value);
	}

	/**
	 * Getter for <code>ae_autosubs.experiments.annotare_submission_id</code>. 
	 */
	public java.lang.Integer getAnnotareSubmissionId() {
		return (java.lang.Integer) getValue(40);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExperimentsRecord
	 */
	public ExperimentsRecord() {
		super(uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Experiments.EXPERIMENTS);
	}
}
