/*
 * This file is generated by jOOQ.
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Experiments;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentsRecord extends UpdatableRecordImpl<ExperimentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ae_autosubs.experiments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.accession</code>.
     */
    public void setAccession(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.accession</code>.
     */
    public String getAccession() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.checker_score</code>.
     */
    public void setCheckerScore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.checker_score</code>.
     */
    public Integer getCheckerScore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.software</code>.
     */
    public void setSoftware(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.software</code>.
     */
    public String getSoftware() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.data_warehouse_ready</code>.
     */
    public void setDataWarehouseReady(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.data_warehouse_ready</code>.
     */
    public Integer getDataWarehouseReady() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.date_last_edited</code>.
     */
    public void setDateLastEdited(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.date_last_edited</code>.
     */
    public LocalDateTime getDateLastEdited() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.date_submitted</code>.
     */
    public void setDateSubmitted(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.date_submitted</code>.
     */
    public LocalDateTime getDateSubmitted() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.date_last_processed</code>.
     */
    public void setDateLastProcessed(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.date_last_processed</code>.
     */
    public LocalDateTime getDateLastProcessed() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.in_curation</code>.
     */
    public void setInCuration(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.in_curation</code>.
     */
    public Integer getInCuration() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.curator</code>.
     */
    public void setCurator(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.curator</code>.
     */
    public String getCurator() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.comment</code>.
     */
    public void setComment(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.comment</code>.
     */
    public String getComment() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.experiment_type</code>.
     */
    public void setExperimentType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.experiment_type</code>.
     */
    public String getExperimentType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.miamexpress_login</code>.
     */
    public void setMiamexpressLogin(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.miamexpress_login</code>.
     */
    public String getMiamexpressLogin() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.miamexpress_subid</code>.
     */
    public void setMiamexpressSubid(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.miamexpress_subid</code>.
     */
    public Integer getMiamexpressSubid() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.is_affymetrix</code>.
     */
    public void setIsAffymetrix(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.is_affymetrix</code>.
     */
    public Integer getIsAffymetrix() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.is_uhts</code>.
     */
    public void setIsUhts(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.is_uhts</code>.
     */
    public Integer getIsUhts() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.use_native_datafiles</code>.
     */
    public void setUseNativeDatafiles(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.use_native_datafiles</code>.
     */
    public Integer getUseNativeDatafiles() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.is_mx_batchloader</code>.
     */
    public void setIsMxBatchloader(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.is_mx_batchloader</code>.
     */
    public Integer getIsMxBatchloader() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.miame_score</code>.
     */
    public void setMiameScore(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.miame_score</code>.
     */
    public Integer getMiameScore() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.in_data_warehouse</code>.
     */
    public void setInDataWarehouse(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.in_data_warehouse</code>.
     */
    public Integer getInDataWarehouse() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.num_submissions</code>.
     */
    public void setNumSubmissions(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.num_submissions</code>.
     */
    public Integer getNumSubmissions() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.submitter_description</code>.
     */
    public void setSubmitterDescription(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.submitter_description</code>.
     */
    public String getSubmitterDescription() {
        return (String) get(25);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.curated_name</code>.
     */
    public void setCuratedName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.curated_name</code>.
     */
    public String getCuratedName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.num_samples</code>.
     */
    public void setNumSamples(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.num_samples</code>.
     */
    public Integer getNumSamples() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.num_hybridizations</code>.
     */
    public void setNumHybridizations(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.num_hybridizations</code>.
     */
    public Integer getNumHybridizations() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.has_raw_data</code>.
     */
    public void setHasRawData(Integer value) {
        set(29, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.has_raw_data</code>.
     */
    public Integer getHasRawData() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.has_processed_data</code>.
     */
    public void setHasProcessedData(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.has_processed_data</code>.
     */
    public Integer getHasProcessedData() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.has_gds</code>.
     */
    public void setHasGds(Byte value) {
        set(31, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.has_gds</code>.
     */
    public Byte getHasGds() {
        return (Byte) get(31);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.release_date</code>.
     */
    public void setReleaseDate(LocalDateTime value) {
        set(32, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.release_date</code>.
     */
    public LocalDateTime getReleaseDate() {
        return (LocalDateTime) get(32);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.is_released</code>.
     */
    public void setIsReleased(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.is_released</code>.
     */
    public Integer getIsReleased() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.ae_miame_score</code>.
     */
    public void setAeMiameScore(Integer value) {
        set(34, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.ae_miame_score</code>.
     */
    public Integer getAeMiameScore() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.migration_status</code>.
     */
    public void setMigrationStatus(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.migration_status</code>.
     */
    public String getMigrationStatus() {
        return (String) get(35);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.migration_comment</code>.
     */
    public void setMigrationComment(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.migration_comment</code>.
     */
    public String getMigrationComment() {
        return (String) get(36);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.migration_source</code>.
     */
    public void setMigrationSource(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.migration_source</code>.
     */
    public String getMigrationSource() {
        return (String) get(37);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.file_to_load</code>.
     */
    public void setFileToLoad(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.file_to_load</code>.
     */
    public String getFileToLoad() {
        return (String) get(38);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.atlas_fail_score</code>.
     */
    public void setAtlasFailScore(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.atlas_fail_score</code>.
     */
    public String getAtlasFailScore() {
        return (String) get(39);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.annotare_submission_id</code>.
     */
    public void setAnnotareSubmissionId(Integer value) {
        set(40, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.annotare_submission_id</code>.
     */
    public Integer getAnnotareSubmissionId() {
        return (Integer) get(40);
    }

    /**
     * Setter for <code>ae_autosubs.experiments.file_validation_status</code>.
     */
    public void setFileValidationStatus(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>ae_autosubs.experiments.file_validation_status</code>.
     */
    public String getFileValidationStatus() {
        return (String) get(41);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperimentsRecord
     */
    public ExperimentsRecord() {
        super(Experiments.EXPERIMENTS);
    }

    /**
     * Create a detached, initialised ExperimentsRecord
     */
    public ExperimentsRecord(Integer id, String accession, String name, Integer userId, Integer checkerScore, String software, String status, Integer dataWarehouseReady, LocalDateTime dateLastEdited, LocalDateTime dateSubmitted, LocalDateTime dateLastProcessed, Integer inCuration, String curator, String comment, String experimentType, String miamexpressLogin, Integer miamexpressSubid, Integer isAffymetrix, Integer isUhts, Integer useNativeDatafiles, Integer isMxBatchloader, Integer isDeleted, Integer miameScore, Integer inDataWarehouse, Integer numSubmissions, String submitterDescription, String curatedName, Integer numSamples, Integer numHybridizations, Integer hasRawData, Integer hasProcessedData, Byte hasGds, LocalDateTime releaseDate, Integer isReleased, Integer aeMiameScore, String migrationStatus, String migrationComment, String migrationSource, String fileToLoad, String atlasFailScore, Integer annotareSubmissionId, String fileValidationStatus) {
        super(Experiments.EXPERIMENTS);

        setId(id);
        setAccession(accession);
        setName(name);
        setUserId(userId);
        setCheckerScore(checkerScore);
        setSoftware(software);
        setStatus(status);
        setDataWarehouseReady(dataWarehouseReady);
        setDateLastEdited(dateLastEdited);
        setDateSubmitted(dateSubmitted);
        setDateLastProcessed(dateLastProcessed);
        setInCuration(inCuration);
        setCurator(curator);
        setComment(comment);
        setExperimentType(experimentType);
        setMiamexpressLogin(miamexpressLogin);
        setMiamexpressSubid(miamexpressSubid);
        setIsAffymetrix(isAffymetrix);
        setIsUhts(isUhts);
        setUseNativeDatafiles(useNativeDatafiles);
        setIsMxBatchloader(isMxBatchloader);
        setIsDeleted(isDeleted);
        setMiameScore(miameScore);
        setInDataWarehouse(inDataWarehouse);
        setNumSubmissions(numSubmissions);
        setSubmitterDescription(submitterDescription);
        setCuratedName(curatedName);
        setNumSamples(numSamples);
        setNumHybridizations(numHybridizations);
        setHasRawData(hasRawData);
        setHasProcessedData(hasProcessedData);
        setHasGds(hasGds);
        setReleaseDate(releaseDate);
        setIsReleased(isReleased);
        setAeMiameScore(aeMiameScore);
        setMigrationStatus(migrationStatus);
        setMigrationComment(migrationComment);
        setMigrationSource(migrationSource);
        setFileToLoad(fileToLoad);
        setAtlasFailScore(atlasFailScore);
        setAnnotareSubmissionId(annotareSubmissionId);
        setFileValidationStatus(fileValidationStatus);
    }
}
