/*
 * This file is generated by jOOQ.
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesUsersRecord extends TableRecordImpl<RolesUsersRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ae_autosubs.roles_users.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ae_autosubs.roles_users.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ae_autosubs.roles_users.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ae_autosubs.roles_users.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RolesUsers.ROLES_USERS.USER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RolesUsers.ROLES_USERS.ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public Integer component2() {
        return getRoleId();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public Integer value2() {
        return getRoleId();
    }

    @Override
    public RolesUsersRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public RolesUsersRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolesUsersRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesUsersRecord
     */
    public RolesUsersRecord() {
        super(RolesUsers.ROLES_USERS);
    }

    /**
     * Create a detached, initialised RolesUsersRecord
     */
    public RolesUsersRecord(Integer userId, Integer roleId) {
        super(RolesUsers.ROLES_USERS);

        setUserId(userId);
        setRoleId(roleId);
    }
}
