/*
 * This file is generated by jOOQ.
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpreadsheetsRecord extends UpdatableRecordImpl<SpreadsheetsRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ae_autosubs.spreadsheets.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ae_autosubs.spreadsheets.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ae_autosubs.spreadsheets.experiment_id</code>.
     */
    public void setExperimentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ae_autosubs.spreadsheets.experiment_id</code>.
     */
    public Integer getExperimentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ae_autosubs.spreadsheets.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ae_autosubs.spreadsheets.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ae_autosubs.spreadsheets.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ae_autosubs.spreadsheets.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Spreadsheets.SPREADSHEETS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Spreadsheets.SPREADSHEETS.EXPERIMENT_ID;
    }

    @Override
    public Field<String> field3() {
        return Spreadsheets.SPREADSHEETS.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Spreadsheets.SPREADSHEETS.IS_DELETED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getExperimentId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getIsDeleted();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getExperimentId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getIsDeleted();
    }

    @Override
    public SpreadsheetsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SpreadsheetsRecord value2(Integer value) {
        setExperimentId(value);
        return this;
    }

    @Override
    public SpreadsheetsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public SpreadsheetsRecord value4(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SpreadsheetsRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpreadsheetsRecord
     */
    public SpreadsheetsRecord() {
        super(Spreadsheets.SPREADSHEETS);
    }

    /**
     * Create a detached, initialised SpreadsheetsRecord
     */
    public SpreadsheetsRecord(Integer id, Integer experimentId, String name, Integer isDeleted) {
        super(Spreadsheets.SPREADSHEETS);

        setId(id);
        setExperimentId(experimentId);
        setName(name);
        setIsDeleted(isDeleted);
    }
}
