/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = 796108732;

	/**
	 * Setter for <code>ae_autosubs.users.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ae_autosubs.users.login</code>. 
	 */
	public void setLogin(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.login</code>. 
	 */
	public java.lang.String getLogin() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ae_autosubs.users.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ae_autosubs.users.password</code>. 
	 */
	public void setPassword(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.password</code>. 
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ae_autosubs.users.email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ae_autosubs.users.modified_at</code>. 
	 */
	public void setModifiedAt(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.modified_at</code>. 
	 */
	public java.sql.Timestamp getModifiedAt() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>ae_autosubs.users.created_at</code>. 
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.created_at</code>. 
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>ae_autosubs.users.access</code>. 
	 */
	public void setAccess(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.access</code>. 
	 */
	public java.sql.Timestamp getAccess() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>ae_autosubs.users.is_deleted</code>. 
	 */
	public void setIsDeleted(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ae_autosubs.users.is_deleted</code>. 
	 */
	public java.lang.Integer getIsDeleted() {
		return (java.lang.Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.MODIFIED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.ACCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS.IS_DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getModifiedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getAccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getIsDeleted();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS);
	}
}
