/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataFiles extends org.jooq.impl.TableImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord> {

	private static final long serialVersionUID = -885817549;

	/**
	 * The singleton instance of <code>ae_autosubs.data_files</code>
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles DATA_FILES = new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord> getRecordType() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord.class;
	}

	/**
	 * The column <code>ae_autosubs.data_files.id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.data_files.experiment_id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, java.lang.Integer> EXPERIMENT_ID = createField("experiment_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.data_files.name</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>ae_autosubs.data_files.is_unpacked</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, java.lang.Integer> IS_UNPACKED = createField("is_unpacked", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.data_files.is_deleted</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, java.lang.Integer> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>ae_autosubs.data_files</code> table reference
	 */
	public DataFiles() {
		super("data_files", uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS);
	}

	/**
	 * Create an aliased <code>ae_autosubs.data_files</code> table reference
	 */
	public DataFiles(java.lang.String alias) {
		super(alias, uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS, uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles.DATA_FILES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, java.lang.Integer> getIdentity() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.IDENTITY_DATA_FILES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord> getPrimaryKey() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_DATA_FILES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_DATA_FILES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.DataFilesRecord, ?>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.DATA_FILES_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles as(java.lang.String alias) {
		return new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles(alias);
	}
}
