/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends org.jooq.impl.TableImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord> {

	private static final long serialVersionUID = -1008876466;

	/**
	 * The singleton instance of <code>ae_autosubs.roles</code>
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles ROLES = new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord> getRecordType() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord.class;
	}

	/**
	 * The column <code>ae_autosubs.roles.id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.roles.name</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>ae_autosubs.roles.info</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord, java.lang.String> INFO = createField("info", org.jooq.impl.SQLDataType.VARCHAR.length(80), this);

	/**
	 * The column <code>ae_autosubs.roles.is_deleted</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord, java.lang.Integer> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>ae_autosubs.roles</code> table reference
	 */
	public Roles() {
		super("roles", uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS);
	}

	/**
	 * Create an aliased <code>ae_autosubs.roles</code> table reference
	 */
	public Roles(java.lang.String alias) {
		super(alias, uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS, uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles.ROLES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord, java.lang.Integer> getIdentity() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.IDENTITY_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord> getPrimaryKey() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_ROLES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesRecord>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_ROLES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles as(java.lang.String alias) {
		return new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles(alias);
	}
}
