/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>AE2</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScLabelRecord> PK_SC_LABEL_NAME = UniqueKeys0.PK_SC_LABEL_NAME;
	public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScOwnerRecord> PK_SC_OWNER_ID = UniqueKeys0.PK_SC_OWNER_ID;
	public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> PK_SC_USER_ID = UniqueKeys0.PK_SC_USER_ID;
	public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.StudyRecord> PK_STDY_ID = UniqueKeys0.PK_STDY_ID;
	public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.StudyRecord> UK_STDY_ACC = UniqueKeys0.UK_STDY_ACC;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScOwnerRecord, uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScLabelRecord> FK_SC_OWNER_SLID_SC_LABEL_ID = ForeignKeys0.FK_SC_OWNER_SLID_SC_LABEL_ID;
	public static final org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScOwnerRecord, uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> FK_SC_OWNER_SUID_SC_USER_ID = ForeignKeys0.FK_SC_OWNER_SUID_SC_USER_ID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScLabelRecord> PK_SC_LABEL_NAME = createUniqueKey(uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL.ID);
		public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScOwnerRecord> PK_SC_OWNER_ID = createUniqueKey(uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER.ID);
		public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> PK_SC_USER_ID = createUniqueKey(uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER.ID);
		public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.StudyRecord> PK_STDY_ID = createUniqueKey(uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY, uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.ID);
		public static final org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.StudyRecord> UK_STDY_ACC = createUniqueKey(uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY, uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.ACC);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScOwnerRecord, uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScLabelRecord> FK_SC_OWNER_SLID_SC_LABEL_ID = createForeignKey(uk.ac.ebi.fg.annotare2.ae.jooq.Keys.PK_SC_LABEL_NAME, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER.SC_LABEL_ID);
		public static final org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScOwnerRecord, uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> FK_SC_OWNER_SUID_SC_USER_ID = createForeignKey(uk.ac.ebi.fg.annotare2.ae.jooq.Keys.PK_SC_USER_ID, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER.SC_USER_ID);
	}
}
