/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScUserRecord extends org.jooq.impl.UpdatableRecordImpl<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> implements org.jooq.Record5<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1884190457;

	/**
	 * Setter for <code>AE2.SC_USER.ID</code>. 
	 */
	public void setId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>AE2.SC_USER.ID</code>. 
	 */
	public java.math.BigInteger getId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>AE2.SC_USER.USERNAME</code>. 
	 */
	public void setUsername(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>AE2.SC_USER.USERNAME</code>. 
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>AE2.SC_USER.USERPASSWORD</code>. 
	 */
	public void setUserpassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>AE2.SC_USER.USERPASSWORD</code>. 
	 */
	public java.lang.String getUserpassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>AE2.SC_USER.USEREMAIL</code>. 
	 */
	public void setUseremail(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>AE2.SC_USER.USEREMAIL</code>. 
	 */
	public java.lang.String getUseremail() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>AE2.SC_USER.NOTE</code>. 
	 */
	public void setNote(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>AE2.SC_USER.NOTE</code>. 
	 */
	public java.lang.String getNote() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER.USERPASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER.USEREMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserpassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUseremail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getNote();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ScUserRecord
	 */
	public ScUserRecord() {
		super(uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER);
	}
}
