/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudyRecord extends org.jooq.impl.UpdatableRecordImpl<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.StudyRecord> implements org.jooq.Record8<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date, java.lang.String, java.sql.Date> {

	private static final long serialVersionUID = -1997232594;

	/**
	 * Setter for <code>AE2.STUDY.ID</code>. 
	 */
	public void setId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.ID</code>. 
	 */
	public java.math.BigInteger getId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>AE2.STUDY.ACC</code>. 
	 */
	public void setAcc(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.ACC</code>. 
	 */
	public java.lang.String getAcc() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>AE2.STUDY.DESCRIPTION</code>. 
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.DESCRIPTION</code>. 
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>AE2.STUDY.OBJECTIVE</code>. 
	 */
	public void setObjective(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.OBJECTIVE</code>. 
	 */
	public java.lang.String getObjective() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>AE2.STUDY.RELEASEDATE</code>. 
	 */
	public void setReleasedate(java.sql.Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.RELEASEDATE</code>. 
	 */
	public java.sql.Date getReleasedate() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>AE2.STUDY.SUBMISSIONDATE</code>. 
	 */
	public void setSubmissiondate(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.SUBMISSIONDATE</code>. 
	 */
	public java.sql.Date getSubmissiondate() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>AE2.STUDY.TITLE</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.TITLE</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>AE2.STUDY.LASTUPDATEDATE</code>. 
	 */
	public void setLastupdatedate(java.sql.Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>AE2.STUDY.LASTUPDATEDATE</code>. 
	 */
	public java.sql.Date getLastupdatedate() {
		return (java.sql.Date) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date, java.lang.String, java.sql.Date> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date, java.lang.String, java.sql.Date> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.ACC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.OBJECTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.RELEASEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.SUBMISSIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field8() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY.LASTUPDATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAcc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getObjective();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getReleasedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getSubmissiondate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value8() {
		return getLastupdatedate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudyRecord
	 */
	public StudyRecord() {
		super(uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY);
	}
}
