/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in ae_autosubs
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ae_autosubs.data_files
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles DATA_FILES = uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles.DATA_FILES;

	/**
	 * The table ae_autosubs.experiments
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Experiments EXPERIMENTS = uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Experiments.EXPERIMENTS;

	/**
	 * The table ae_autosubs.roles
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles ROLES = uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles.ROLES;

	/**
	 * The table ae_autosubs.roles_users
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers ROLES_USERS = uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers.ROLES_USERS;

	/**
	 * The table ae_autosubs.spreadsheets
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets SPREADSHEETS = uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets.SPREADSHEETS;

	/**
	 * The table ae_autosubs.users
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users USERS = uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS;
}
