/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesUsers extends org.jooq.impl.TableImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord> {

	private static final long serialVersionUID = 1172035313;

	/**
	 * The singleton instance of <code>ae_autosubs.roles_users</code>
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers ROLES_USERS = new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord> getRecordType() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord.class;
	}

	/**
	 * The column <code>ae_autosubs.roles_users.user_id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.roles_users.role_id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord, java.lang.Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>ae_autosubs.roles_users</code> table reference
	 */
	public RolesUsers() {
		super("roles_users", uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS);
	}

	/**
	 * Create an aliased <code>ae_autosubs.roles_users</code> table reference
	 */
	public RolesUsers(java.lang.String alias) {
		super(alias, uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS, uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers.ROLES_USERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.RolesUsersRecord, ?>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.ROLES_USERS_IBFK_1, uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.ROLES_USERS_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers as(java.lang.String alias) {
		return new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers(alias);
	}
}
