/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spreadsheets extends org.jooq.impl.TableImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord> {

	private static final long serialVersionUID = -608862123;

	/**
	 * The singleton instance of <code>ae_autosubs.spreadsheets</code>
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets SPREADSHEETS = new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord> getRecordType() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord.class;
	}

	/**
	 * The column <code>ae_autosubs.spreadsheets.id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.spreadsheets.experiment_id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, java.lang.Integer> EXPERIMENT_ID = createField("experiment_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.spreadsheets.name</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>ae_autosubs.spreadsheets.is_deleted</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, java.lang.Integer> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>ae_autosubs.spreadsheets</code> table reference
	 */
	public Spreadsheets() {
		super("spreadsheets", uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS);
	}

	/**
	 * Create an aliased <code>ae_autosubs.spreadsheets</code> table reference
	 */
	public Spreadsheets(java.lang.String alias) {
		super(alias, uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS, uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets.SPREADSHEETS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, java.lang.Integer> getIdentity() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.IDENTITY_SPREADSHEETS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord> getPrimaryKey() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_SPREADSHEETS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_SPREADSHEETS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.SpreadsheetsRecord, ?>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.SPREADSHEETS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets as(java.lang.String alias) {
		return new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets(alias);
	}
}
