/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord> {

	private static final long serialVersionUID = -568661623;

	/**
	 * The singleton instance of <code>ae_autosubs.users</code>
	 */
	public static final uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users USERS = new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord> getRecordType() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>ae_autosubs.users.id</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>ae_autosubs.users.login</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>ae_autosubs.users.name</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>ae_autosubs.users.password</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>ae_autosubs.users.email</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this);

	/**
	 * The column <code>ae_autosubs.users.modified_at</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.sql.Timestamp> MODIFIED_AT = createField("modified_at", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>ae_autosubs.users.created_at</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>ae_autosubs.users.access</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.sql.Timestamp> ACCESS = createField("access", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>ae_autosubs.users.is_deleted</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.Integer> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>ae_autosubs.users</code> table reference
	 */
	public Users() {
		super("users", uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS);
	}

	/**
	 * Create an aliased <code>ae_autosubs.users</code> table reference
	 */
	public Users(java.lang.String alias) {
		super(alias, uk.ac.ebi.fg.annotare2.autosubs.jooq.AeAutosubs.AE_AUTOSUBS, uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users.USERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord, java.lang.Integer> getIdentity() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.IDENTITY_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord> getPrimaryKey() {
		return uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.records.UsersRecord>>asList(uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_USERS_PRIMARY, uk.ac.ebi.fg.annotare2.autosubs.jooq.Keys.KEY_USERS_LOGIN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users as(java.lang.String alias) {
		return new uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users(alias);
	}
}
