/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScUser extends org.jooq.impl.TableImpl<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> {

	private static final long serialVersionUID = 1453871919;

	/**
	 * The singleton instance of <code>AE2.SC_USER</code>
	 */
	public static final uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser SC_USER = new uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> getRecordType() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord.class;
	}

	/**
	 * The column <code>AE2.SC_USER.ID</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord, java.math.BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(19), this);

	/**
	 * The column <code>AE2.SC_USER.USERNAME</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord, java.lang.String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR.length(400), this);

	/**
	 * The column <code>AE2.SC_USER.USERPASSWORD</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord, java.lang.String> USERPASSWORD = createField("USERPASSWORD", org.jooq.impl.SQLDataType.VARCHAR.length(400), this);

	/**
	 * The column <code>AE2.SC_USER.USEREMAIL</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord, java.lang.String> USEREMAIL = createField("USEREMAIL", org.jooq.impl.SQLDataType.VARCHAR.length(400), this);

	/**
	 * The column <code>AE2.SC_USER.NOTE</code>. 
	 */
	public final org.jooq.TableField<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord, java.lang.String> NOTE = createField("NOTE", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this);

	/**
	 * Create a <code>AE2.SC_USER</code> table reference
	 */
	public ScUser() {
		super("SC_USER", uk.ac.ebi.fg.annotare2.ae.jooq.Ae2.AE2);
	}

	/**
	 * Create an aliased <code>AE2.SC_USER</code> table reference
	 */
	public ScUser(java.lang.String alias) {
		super(alias, uk.ac.ebi.fg.annotare2.ae.jooq.Ae2.AE2, uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord> getPrimaryKey() {
		return uk.ac.ebi.fg.annotare2.ae.jooq.Keys.PK_SC_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<uk.ac.ebi.fg.annotare2.ae.jooq.tables.records.ScUserRecord>>asList(uk.ac.ebi.fg.annotare2.ae.jooq.Keys.PK_SC_USER_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser as(java.lang.String alias) {
		return new uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser(alias);
	}
}
