/*
 * Copyright 2009-2016 European Molecular Biology Laboratory
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.ac.ebi.fg.annotare2.submission.model;

/**
 * @author Olga Melnichuk
 */
public enum FileType implements EnumWithHelpText{

    RAW_FILE("Raw", "The \"native\" files generated by the microarray scanner software (e.g. .CEL, .gpr) or sequencing machine (.fastq.gz) <br/><a href=\"https://www.ebi.ac.uk/fg/annotare/help/accepted_raw_ma_file_formats.html\" target=\"_blank\"><i class=\"fa fa-life-ring\" aria-hidden=\"true\"></i>Accepted microarray raw file formats</a><br/><a href=\"http://www.ebi.ac.uk/arrayexpress/help/UHTS_submissions.html#raw_data_files\" target=\"_blank\"><i class=\"fa fa-life-ring\" aria-hidden=\"true\"></i>Accepted sequencing raw file formats</a> "),

    RAW_MATRIX_FILE("Raw Matrix", "A raw file in tab-delimited text (.txt) format, that contains data from more than one assay (probes/genes in rows, assays in columns) <br/><a href=\"https://www.ebi.ac.uk/fg/annotare/help/strict_mtab_matrix.html\" target=\"_blank\"><i class=\"fa fa-life-ring\" aria-hidden=\"true\"></i>Accepted matrix file formats</a>"),

    PROCESSED_FILE("Processed", "A tab-delimited text (.txt) file containing data from a single assay <br/><a href=\"https://www.ebi.ac.uk/fg/annotare/help/accepted_processed_ma_file_formats.html\" target=\"_blank\"><i class=\"fa fa-life-ring\" aria-hidden=\"true\"></i>Accepted microarray processed file formats</a><br/><a href=\"https://www.ebi.ac.uk/arrayexpress/help/UHTS_submissions.html#processed_data\" target=\"_blank\"><i class=\"fa fa-life-ring\" aria-hidden=\"true\"></i>Accepted sequencing processed file formats</a> "),

    PROCESSED_MATRIX_FILE("Processed Matrix", "A tab-delimited text (.txt) file of very strict format, containing data from more than one assay <br/><a href=\"https://www.ebi.ac.uk/fg/annotare/help/strict_mtab_matrix.html\" target=\"_blank\"><i class=\"fa fa-life-ring\" aria-hidden=\"true\"></i>Accepted matrix file formats</a>");

    private final String title;
    private final String helpText;

    FileType(String title, String helpText) {
        this.title = title;
        this.helpText = helpText;
    }

    public String getHelpText() {
        return helpText;
    }


    public String getTitle() {
        return title;
    }

    @Override
    public String toString() {
        return title;
    }

    @SuppressWarnings("unused")
    public boolean isRaw() {
        return RAW_FILE == this || RAW_MATRIX_FILE == this;
    }

    @SuppressWarnings("unused")
    public boolean isProcessed() {
        return PROCESSED_FILE == this || PROCESSED_MATRIX_FILE == this;
    }

    @SuppressWarnings("unused")
    public boolean isFGEM() {
        return RAW_MATRIX_FILE == this || PROCESSED_MATRIX_FILE == this;
    }
}
