apiVersion: v1
kind: Pod
spec:
  restartPolicy: Never
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      imagePullPolicy: IfNotPresent
      command: ["cat"]
      tty: true
      stdin: true
      workingDir: /home/jenkins/agent
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
          readOnly: false
  volumes:
    - name: workspace-volume
      emptyDir: {}
