apiVersion: v1
kind: Pod
metadata:
  labels:
    app: annotare-maven-agent
spec:
  restartPolicy: Never
  nodeSelector:
    status: healthy
  initContainers:
    - name: install-git
      image: alpine/git
      command: ["apk", "add", "git"]
      volumeMounts:
        - name: shared-data
          mountPath: /data
  containers:
    - name: maven
      # Use Maven 3.6.3 (pre-3.8) to allow HTTP repositories without requiring allowInsecureProtocol
      image: maven:3.6.3-jdk-8
      imagePullPolicy: IfNotPresent
      # Use a long-running, lightweight command to ensure the container is always exec-ready
      command: ["sh", "-c", "sleep 365d"]
      tty: true
      stdin: true
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      env:
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/root/.m2/repository -XX:MaxRAMPercentage=75.0 -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: shared-data
          mountPath: /data
    - name: mysql
      image: mysql:5.7
      imagePullPolicy: IfNotPresent
      args:
        - "--sql-mode=ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      env:
        - name: MYSQL_DATABASE
          value: "annotare"
        - name: MYSQL_USER
          value: "annotare"
        - name: MYSQL_PASSWORD
          value: "annotare"
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumes:
    - name: maven-repo
      emptyDir: {}
    - name: workspace-volume
      emptyDir: {}
    - name: shared-data
      emptyDir: {}
    - name: mysql-data
      emptyDir: {}
