apiVersion: v1
kind: Pod
metadata:
  labels:
    app: annotare-maven-agent
spec:
  restartPolicy: Never
  nodeSelector:
    status: healthy
  initContainers:
    - name: install-git
      image: alpine/git
      command: ["apk", "add", "git"]
      volumeMounts:
        - name: shared-data
          mountPath: /data
  containers:
    - name: maven
      # Maven image includes an OpenJDK distribution via Eclipse Temurin (compatible with OpenJDK)
      image: maven:3.8.8-eclipse-temurin-8
      imagePullPolicy: IfNotPresent
      # Use a long-running, lightweight command to ensure the container is always exec-ready
      command: ["sh", "-c", "sleep 365d"]
      tty: true
      stdin: true
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      env:
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/root/.m2/repository -XX:MaxRAMPercentage=75.0"
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: shared-data
          mountPath: /data
  volumes:
    - name: maven-repo
      emptyDir: {}
    - name: workspace-volume
      emptyDir: {}
    - name: shared-data
      emptyDir: {}
