pipeline {
    options {
        copyArtifactPermission('Annotare-release-wwwdev, Annotare-release-prod');
    }
    agent any
    tools {
        maven 'maven-3.8.5'
        jdk 'jdk-8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    echo "JAVA_HOME = ${JAVA_HOME}"
                '''
            }
        }

        stage ('Compile') {
            steps{
               configFileProvider([configFile(fileId: 'annotare_wwwdev_maven_settings', variable: 'MAVEN_SETTINGS_XML')]) {
                    sh 'mvn -U --batch-mode -s $MAVEN_SETTINGS_XML -f app/pom.xml clean compile'
                }
            }
        }

        stage ('Test') {
            steps{
               configFileProvider([configFile(fileId: 'annotare_wwwdev_maven_settings', variable: 'MAVEN_SETTINGS_XML')]) {
                    sh 'mvn -U --batch-mode -s $MAVEN_SETTINGS_XML -f app/pom.xml test'
                }
            }
        }

        stage ('Build Artifacts') {
            steps{
               configFileProvider([configFile(fileId: 'annotare_wwwdev_maven_settings', variable: 'MAVEN_DEV_SETTINGS_XML'),
                                    configFile(fileId: 'annotare_prod_maven_settings', variable: 'MAVEN_PROD_SETTINGS_XML')]) {
                    if(env.BRANCH_NAME != 'master'){
                        sh 'mvn -U --batch-mode -s $MAVEN_DEV_SETTINGS_XML -f app/pom.xml package'
                    } else{
                        sh 'mvn -U --batch-mode -s $MAVEN_PROD_SETTINGS_XML -f app/pom.xml package'
                    }
                    archiveArtifacts artifacts: 'app/webapp/target/annotare2-web*.war', fingerprint: true
               }
            }
        }

        stage ('Release') {
            when {
                expression {
                    return env.BRANCH_NAME != 'master';
                }
            }
            steps{
                release job: 'Annotare-web-app-release-wwwdev', parameters: [string(name: 'artifactBuildNumber', value: env.BUILD_NUMBER), string(name: 'branch_name', value: env.BRANCH_NAME)]
            }
        }

        stage ('Production Release') {
            when {
                branch 'master'
            }
            steps{
                release job: 'Annotare-web-app-release-prod', parameters: [string(name: 'artifactBuildNumber', value: env.BUILD_NUMBER), string(name: 'branch_name', value: env.BRANCH_NAME)]
            }
        }
    }
}