/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ae2 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1468658437;

	/**
	 * The singleton instance of <code>AE2</code>
	 */
	public static final Ae2 AE2 = new Ae2();

	/**
	 * No further instances allowed
	 */
	private Ae2() {
		super("AE2");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL,
			uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER,
			uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER,
			uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY);
	}
}
