/**
 * This class is generated by jOOQ
 */
package uk.ac.ebi.fg.annotare2.ae.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in AE2
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table AE2.SC_LABEL
	 */
	public static final uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel SC_LABEL = uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScLabel.SC_LABEL;

	/**
	 * The table AE2.SC_OWNER
	 */
	public static final uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner SC_OWNER = uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScOwner.SC_OWNER;

	/**
	 * The table AE2.SC_USER
	 */
	public static final uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser SC_USER = uk.ac.ebi.fg.annotare2.ae.jooq.tables.ScUser.SC_USER;

	/**
	 * The table AE2.STUDY
	 */
	public static final uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study STUDY = uk.ac.ebi.fg.annotare2.ae.jooq.tables.Study.STUDY;
}
