/*
 * This file is generated by jOOQ.
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Experiments;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AeAutosubs extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ae_autosubs</code>
     */
    public static final AeAutosubs AE_AUTOSUBS = new AeAutosubs();

    /**
     * The table <code>ae_autosubs.data_files</code>.
     */
    public final DataFiles DATA_FILES = DataFiles.DATA_FILES;

    /**
     * The table <code>ae_autosubs.experiments</code>.
     */
    public final Experiments EXPERIMENTS = Experiments.EXPERIMENTS;

    /**
     * The table <code>ae_autosubs.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>ae_autosubs.roles_users</code>.
     */
    public final RolesUsers ROLES_USERS = RolesUsers.ROLES_USERS;

    /**
     * The table <code>ae_autosubs.spreadsheets</code>.
     */
    public final Spreadsheets SPREADSHEETS = Spreadsheets.SPREADSHEETS;

    /**
     * The table <code>ae_autosubs.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private AeAutosubs() {
        super("ae_autosubs", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DataFiles.DATA_FILES,
            Experiments.EXPERIMENTS,
            Roles.ROLES,
            RolesUsers.ROLES_USERS,
            Spreadsheets.SPREADSHEETS,
            Users.USERS);
    }
}
