/*
 * This file is generated by jOOQ.
 */
package uk.ac.ebi.fg.annotare2.autosubs.jooq;


import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.DataFiles;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Experiments;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Roles;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.RolesUsers;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Spreadsheets;
import uk.ac.ebi.fg.annotare2.autosubs.jooq.tables.Users;


/**
 * Convenience access to all tables in ae_autosubs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ae_autosubs.data_files</code>.
     */
    public static final DataFiles DATA_FILES = DataFiles.DATA_FILES;

    /**
     * The table <code>ae_autosubs.experiments</code>.
     */
    public static final Experiments EXPERIMENTS = Experiments.EXPERIMENTS;

    /**
     * The table <code>ae_autosubs.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>ae_autosubs.roles_users</code>.
     */
    public static final RolesUsers ROLES_USERS = RolesUsers.ROLES_USERS;

    /**
     * The table <code>ae_autosubs.spreadsheets</code>.
     */
    public static final Spreadsheets SPREADSHEETS = Spreadsheets.SPREADSHEETS;

    /**
     * The table <code>ae_autosubs.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
